"getting parsererror (a custom exception), even though the conditions for the exception are not met. i've shown my code below when i assign value to word_list at the by default, the program works fine. but when i assign value to word_list by getting it from use through raw_input(), i get parsererror, even though the input is correct...i am unable to understand as to why this is happening. any help would be greatly appreciated...here is my code:..def parse_subject(word_list):.    skip(word_list,'stop').    word_type = peek(word_list).    if word_type == 'noun':.       return match(word_list).    elif word_type == 'verb':.        return 'player'.    else:.        raise parsererror(""expected a noun or verb next"")..def parse_verb(word_list):.    skip(word_list,'stop').    word_type = peek(word_list).    if word_type == 'verb':.        return match(word_list).    else:.        raise parsererror(""expected a verb next"")..def parse_object(word_list):.    skip(word_list,'stop').    word_type = peek(word_list).    if word_type == 'noun':.        return match(word_list).    else:.        raise parsererror(""expected a object next"")...def peek(word_list):.    if word_list:.         word = word_list[0].         return word[0].    else:.        return none..def match(word_list):.    word = word_list.pop(0).    return word[1]..def skip(word_list, word_type):.    if word_list:.        while peek(word_list) == word_type:.            word_list.pop(0)..class sentence():.    def __init__(self, word_list):.        self.word_list = word_list...    def result(self):.        return parse_subject(self.word_list), parse_verb(self.word_list), parse_object(self.word_list)..word_list = [('verb', 'going'), ('stop', 'go'), ('noun', 'temple')]..sentence_ob = sentence(word_list).print sentence_ob.result()"
