"strange about subprocess.call in blank because the subprocess.call invoke cmd .exe flash off, just return value '1', which indicates a run error. i only screenshot to explain...under win cmd, it runs well. why does it break in subprocess.call?..year:    979.year:    980.year:    981.year:    982.year:    983.year:    984.year:    985.year:    986.year:    987.year:    988.year:    989.spinup: residual trend  = -0.000069.spinup: number of years = 990.h:calibrationbgcclimb&gt;pointbgc.exe .inispinupt59_13_79_29_11_80_8.ini...use subproceess.call in blank: return value '1' ,not '0'.. subprocess.call([r'h:calibrationbgcclimbpointbgc.exe',r'.inispinupt59_13_79_29_11_80_8.ini']).out[7]: 1...use subprocess.popen check stderr:..process = subprocess.popen([r'h:calibrationbgcclimbpointbgc.exe',r'.inispinupt59_13_79_29_11_80_8.ini'], shell=true,stdout=subprocess.pipe,stderr=subprocess.pipe).out, err = process.communicate().errcode = process.returncode..err. out[3]: b""can't open .\ini\spinup\t59_13_79_29_11_80_8.ini for ascii read ... exitingrnerror opening init file, pointbgc.crn"""
