"how to call blank function call subsequently i have a blank function which is working as expected when called first time..as soon as i add another call it is errors out ""indexerror: list index out of range""..import os.import re.import glob..ldir=""/data/reports/get-snapshots/labs"".pdir=""/data/reports/get-snapsnots/prod""...def get_latest_snap_files(path, *paths):.    snap_path=os.path.join(path, *paths).    snap_file=sorted(glob.iglob(snap_path), key=os.path.getctime, reverse=true).    return snap_file[0]..def main():.    l=get_latest_snap_files(ldir, '*').    print(l).    p=get_latest_snap_files(pdir, '*').    print(p).main()....$blank h.py./data/reports/get-snapshots/labs/labs.snapshot.2019-05-25_184501-out.sorted.log..traceback (most recent call last):.  file ""h.py"", line 24, in &lt;module&gt;.    main().  file ""h.py"", line 22, in main.    p=get_latest_snap_files(pdir, '*').  file ""h.py"", line 16, in get_latest_snap_files.    print(snap_file[0]).indexerror: list index out of range"
