"my created function won't accept an array as one of the arguments i've written a function that takes two arguments, one for no. dimensions and another for no. simulations. the function does exactly what is needed (calculating the volume of a unit hypersphere), however when i wish to plot the function over a range of dimensions it returns an error: ''list' object cannot be interpreted as an integer'...my function is the following,..def hvolume(ndim, nsim):.    ob = [np.random.uniform(0.0,1.0,(nsim, ndim))].    ob = np.concatenate(ob) .    i = 0.    res = [].    while i &lt;= nsim-1:.        arr = np.sqrt(np.sum(np.square(ob[i]))).        i += 1.        res.append(arr).    n = nsim.    n = ndim.    m = len([i for i in res if i &lt;= 1]).    return ((2**n)*m/n)...the error traceback is:..traceback (most recent call last):..file ""&lt;iblank-input-192-4c4a2c778637&gt;"", line 1, in &lt;module&gt;.runfile('h:/documents/blank scripts/q4attempt.py', wdir='h:/documents/blank scripts')..file ""c:usersu1708511appdatalocalcontinuumanaconda3libsite-packagesspyder_kernelscustomizespydercustomize.py"", line 668, in runfile.execfile(filename, namespace)..file ""c:usersu1708511appdatalocalcontinuumanaconda3libsite-packagesspyder_kernelscustomizespydercustomize.py"", line 108, in execfile.exec(compile(f.read(), filename, 'exec'), namespace)..file ""h:/documents/blank scripts/q4attempt.py"", line 20, in &lt;module&gt;.print(hvolume(d, 2))..file ""h:/documents/blank scripts/q4attempt.py"", line 4, in hvolume.ob = [np.random.uniform(0.0,1.0,(nsim, ndim))]..file ""mtrand.pyx"", line 1307, in mtrand.randomstate.uniform..file ""mtrand.pyx"", line 242, in mtrand.cont2_array_sc..typeerror: 'list' object cannot be interpreted as an integer...i really have no idea where to go from here, and have searched thoroughly online for how to resolve this. unfortunately i'm a beginner with this!..any help is appreciated."
