"catch exception thrown from deepest level call in upper method catch the exception on upper class is what i wonder. i have more than one method call layer. in the deepest level, exception is thrown. in the top level how can i catch?..void foo() {.   bar(); &lt;---- catch exception in here.}..void bar() {.   // .... &lt;--- throws ioexception or executionexception or interruptedexception.}..or case two...void foo() {.   bar(); &lt;---- catch exception in here.}..void bar() {.   gbr();.}..void gbr() {.      // .... &lt;--- throws ioexception or executionexception or interruptedexception.}"
